version: "3"

networks:
  sshnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16

volumes:
  opt:
  root:

services:
  node01:
    environment:
      - ROOT_PASSWORD=ubuntu
    image: takeyamajp/ubuntu-sshd
    networks:
      sshnet:
        ipv4_address: 10.1.1.1
    restart: always
  node02:
    image: takeyamajp/rocky-sshd
    networks:
      sshnet:
        ipv4_address: 10.1.1.2
    restart: always
  node03:
    environment:
      - ROOT_PASSWORD=ubuntu
    image: takeyamajp/ubuntu-sshd
    networks:
      sshnet:
        ipv4_address: 10.1.1.3
    volumes:
      - opt:/opt
      - root:/root
    restart: always
    command: ["run-parts", "/root/", "&&", "/usr/sbin/sshd", "-D", "-e"]
  node04:
    environment:
      - ROOT_PASSWORD=ubuntu
    image: takeyamajp/ubuntu-sshd
    networks:
      sshnet:
        ipv4_address: 10.1.1.4
    restart: always
