---

# Ce fichier gère les actions à réaliser sur la machine locale
- name: remplissage fichier hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    search_string: "{{ ansible_host }}"
    line: "{{ ansible_host }} {{ inventory_hostname }}"
    owner: root
    group: root
    mode: '0644'
  delegate_to: localhost
  connection: local

- name: creation dossier inventaire basique
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    mode: '0755'
  delegate_to: localhost
  connection: local
  when: inventory_hostname == groups['nodes'][0]

- name: remplissage inventaire basique
  ansible.builtin.lineinfile:
    path: /etc/ansible/hosts
    search_string: "{{ inventory_hostname }}"
    line: "{{ inventory_hostname }}"
    create: true
    owner: root
    group: root
    mode: '0644'
  delegate_to: localhost
  connection: local
