---

# Ce fichier gère les actions à réaliser pour les cles ssh
- name: obtention cles ssh ips
  ansible.builtin.known_hosts:
    name: "{{ ansible_host }}"
    key: "{{ lookup('ansible.builtin.pipe', 'ssh-keyscan ' + ansible_host) }}"
  delegate_to: localhost
  connection: local

- name: obtention cles ssh noms d'hotes
  ansible.builtin.known_hosts:
    name: "{{ inventory_hostname }}"
    key: "{{ lookup('ansible.builtin.pipe', 'ssh-keyscan ' + inventory_hostname) }}"
  delegate_to: localhost
  connection: local

- name: depose de la cle publique
  ansible.posix.authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  vars:
    ansible_password: "{{ root_password }}"
