---

# Ce fichier gère les actions à réaliser sur la machine locale
- name: template lab
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: /root/docker-compose.yml
    owner: root
    group: root
    mode: '0644'

- name: creation folder lab
  ansible.builtin.file:
    path: /root/ansible/playbook/fablab
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: creation lab
  community.docker.docker_compose_v2:
    project_src: fablab
    files:
    - /root/docker-compose.yml
