version: "3"

services:
  node01:
    command: ["sleep","infinity"]
    image: ubuntu
    networks:
      ssh_net:
    ports:
    - 22:22
    restart: always
  node02:
    command: ["sleep","infinity"]
    image: ubuntu
    networks:
      ssh_net:
    ports:
    - 22:22
    restart: always

networks:
  ssh_net:
