version: "3"

services:
  node01:
    image: ubuntu
    networks:
      ssh_net:
        ipv4_adress: 172.30.2.2
  node02:
    image: ubuntu
    networks:
      ssh_net:
        ipv4_adress: 172.30.3.2

networks:
  ssh_net:
